server.port=8081
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:36000000}
